class LocalizationService {
  // App version - change this once to update everywhere
  static const String appVersion = '1.0.1';

  // Current language: 'vi' or 'en'
  static String language = 'vi';

  // Vietnamese strings
  static const Map<String, String> _vietnamese = {
    // Main Navigation
    'nav_sales': 'Bán Hàng',
    'nav_expenses': 'Chi Tiêu',
    'nav_inventory': 'Kho Hàng',
    'nav_statistics': 'Thống Kê',
    'nav_product_management': 'Quản lý Sản phẩm',
    'nav_data_management': 'Quản lý Dữ liệu',
    'nav_settings': 'Cài đặt',
    'nav_formulas': 'Các công thức cơ bản',
    'nav_privacy': 'Chính sách bảo mật',
    'nav_about': 'About',

    // Privacy Policy Page
    'privacy_access_title': 'Quyền truy cập',
    'privacy_access_content': 'Ứng dụng yêu cầu quyền truy cập kho ảnh khi bạn muốn thêm hình ảnh sản phẩm. Bạn có thể từ chối bất kỳ lúc nào.',
    'privacy_data_title': 'Dữ liệu của bạn',
    'privacy_data_content': 'Tất cả dữ liệu bán hàng của bạn được lưu trữ trên thiết bị. Chúng tôi sử dụng Firebase để phân tích lỗi và Google AdMob để hiển thị quảng cáo. Ngoài ra, chúng tôi không chia sẻ dữ liệu cá nhân của bạn.',
    'privacy_export_title': 'Xuất file dữ liệu CSV và JSON, hoặc String',
    'privacy_export_content': 'Ứng dụng cho phép bạn xuất dữ liệu bán hàng, chi tiêu và kho hàng dưới dạng file CSV, JSON hoặc String để bạn có thể sao lưu hoặc sử dụng trong các ứng dụng khác. Các file này được lưu trong bộ nhớ của thiết bị và hoàn toàn do bạn kiểm soát.',
    'privacy_delete_title': 'Xóa dữ liệu',
    'privacy_delete_content': 'Bạn có thể xóa tất cả dữ liệu của mình bất kỳ lúc nào thông qua mục "Quản lý Dữ liệu" trong menu.',
    'privacy_contact_title': 'Liên hệ',
    'privacy_contact_content': 'Nếu bạn có bất kỳ câu hỏi nào về chính sách bảo mật này, vui lòng liên hệ với chúng tôi.',

    // Settings Page
    'settings_title': 'Cài đặt',
    'settings_display': 'Hiển thị',
    'settings_shop_name': 'Tên cửa hàng',
    'settings_reset_default': 'Đặt lại tên mặc định',
    'settings_dark_mode': 'Chế độ tối',
    'settings_on': 'Bật',
    'settings_off': 'Tắt',
    'settings_currency': 'Tiền tệ',
    'settings_select_currency': 'Chọn loại tiền tệ',
    'settings_sound': 'Âm thanh',
    'settings_sound_on_sale': 'Âm thanh khi bán hàng',
    'settings_products': 'Sản phẩm',
    'settings_default_category': 'Loại sản phẩm mặc định',
    'settings_inventory': 'Kho hàng',
    'settings_low_stock_threshold': 'Ngưỡng sắp hết hàng',
    'settings_notifications': 'Nhận thông báo về kho hàng',
    'settings_version': 'Phiên bản $appVersion',
    'settings_language': 'Ngôn ngữ',
    'settings_select_language': 'Chọn ngôn ngữ',

    // Common Buttons
    'btn_cancel': 'Hủy',
    'btn_back': 'Quay Lại',
    'btn_save': 'Lưu',
    'btn_update': 'Cập nhật',
    'btn_delete': 'Xóa',
    'btn_add': 'Thêm',
    'btn_close': 'Đóng',
    'btn_ok': 'OK',
    'btn_upgrade_pro': 'Upgrade to Pro',

    // Inventory/Products
    'product_name': 'Tên sản phẩm',
    'product_category': 'Loại sản phẩm',
    'product_unit': 'Đơn vị tính',
    'product_quantity': 'Số lượng',
    'product_sell_price': 'Giá bán',
    'product_cost_price': 'Giá vốn',
    'product_current_cost_price': 'Giá vốn hiện tại',
    'product_new_cost_price': 'Giá vốn mới (VND)',
    'product_note': 'Ghi chú',
    'product_categories': 'Loại sản phẩm',
    'product_other': 'Khác',
    'product_add_new_title': 'Thêm sản phẩm mới',
    'product_add_new_subtitle': 'Quản lý sản phẩm',
    'product_empty_hint': 'Nhấn nút + để thêm sản phẩm mới',
    'product_add_inventory_subtitle': 'Quản lý kho hàng',
    'permission_required_title': 'Yêu cầu quyền truy cập',
    'permission_gallery_message': 'Ứng dụng cần quyền truy cập thư viện ảnh để chọn ảnh sản phẩm. Vui lòng cấp quyền trong cài đặt.',
    'btn_open_settings': 'Mở cài đặt',
    'product_edit_title': 'Chỉnh sửa sản phẩm',
    'product_edit_subtitle': 'Cập nhật thông tin',
    'product_select_image': 'Chọn ảnh sản phẩm',
    'product_select_image_hint': 'Nhấn để chọn ảnh',
    'product_selling_price': 'Giá bán (VND)',
    'product_cost_price_label': 'Giá vốn (VND)',
    'product_quantity_label': 'Số lượng hàng',
    'product_category_label': 'Danh mục',
    'product_add_success': 'Thêm sản phẩm "{name}" thành công',
    'product_update_success': 'Cập nhật sản phẩm "{name}" thành công',
    'product_update_error': 'Lỗi khi cập nhật sản phẩm',
    'product_delete_success': 'Đã xóa "{name}"',
    'product_delete_error': 'Lỗi khi xóa sản phẩm',
    'product_delete_confirm_part1': 'Bạn có chắc chắn muốn xóa ',
    'product_delete_confirm_part2': '? Hành động này không thể hoàn tác.',
    'product_delete_confirm_title': 'Xác nhận xóa',

    // Errors
    'error': 'Lỗi',
    'product_fill_required_fields': 'Vui lòng điền đầy đủ thông tin',
    'product_price_must_positive': 'Giá phải dương, số lượng không được âm',
    'product_error_adding': 'Lỗi khi thêm sản phẩm',
    'inventory_update_title': 'Cập nhật kho',
    'inventory_select_image_hint': 'Chọn ảnh mặt hàng',
    'inventory_current_stock': 'Kho hiện tại:',
    'inventory_value': 'Giá trị kho hiện tại',
    'inventory_average_cost_price_note': 'Keto tính giá vốn TRUNG BÌNH khi bạn cập nhật kho hàng với mức giá vốn mới.',
    'inventory_current_cost_price_label': 'Giá vốn hiện tại:',
    'inventory_product_info': 'Thông tin hàng hiện tại:',
    'inventory_current_quantity': 'Số lượng hiện tại:',
    'inventory_average_cost_price': 'Giá vốn trung bình:',
    'inventory_calculation_label': 'Tính toán:',
    'inventory_calculation_formula': 'Công thức: ({old_cost} × {old_quantity} + [giá mới] × [số lượng nhập]) ÷ [số lượng mới]',
    'inventory_selling_price_label': 'Giá bán:',
    'inventory_update_success': 'Cập nhật kho cho "{name}" thành công\nSố lượng: +{quantity}, Giá vốn trung bình: {cost_price}',
    'inventory_update_success_simple': 'Cập nhật kho cho "{name}" thành công',
    'inventory_enter_new_quantity': 'Nhập số lượng mới',
    'inventory_import_different_price': 'Nhập hàng với giá khác',
    'inventory_unit_hint': 'Đơn vị (cái, kg, ly, hộp, phần, ...)',
    'inventory_new_cost_price': 'Giá vốn mới (VND)',
    'inventory_new_quantity_needed': 'Số lượng mới cần nhập',
    'inventory_new_quantity': 'Số lượng mới:',
    'inventory_quantity_negative': 'Số lượng không được âm',
    'inventory_quantity_greater_zero': 'Số lượng phải lớn hơn 0',
    'inventory_cost_greater_zero': 'Giá vốn phải lớn hơn 0',
    'inventory_invalid_value': 'Giá trị không hợp lệ',
    'inventory_fill_all_info': 'Vui lòng điền đầy đủ thông tin',
    'inventory_save_image_error': 'Lỗi khi lưu ảnh sản phẩm',
    'inventory_category_placeholder': 'Danh mục',
    'inventory_search_placeholder': 'Tìm sản phẩm...',
    'inventory_all_categories': 'Tất cả',
    'inventory_permission_gallery': 'Ứng dụng cần quyền truy cập thư viện ảnh để chọn ảnh sản phẩm. Vui lòng bật trong cài đặt.',
    'inventory_low_stock_notification': 'Sắp hết hàng',
    'inventory_out_of_stock': 'Hết hàng / Không Rõ SL',
    'inventory_in_stock': 'Còn hàng',
    'inventory_low_stock': 'Sắp hết',
    'inventory_total': 'Tổng',
    'inventory_in_stock_label': 'Còn hàng',
    'inventory_low_stock_label': 'Sắp hết',
    'inventory_out_of_stock_label': 'Hết hàng /\nKhông Rõ SL',
    'inventory_total_value': 'Giá trị kho\n(VND)',
    'inventory_quick_adjust': 'Điều chỉnh nhanh:',
    'inventory_product_name': 'Tên sản phẩm',
    'inventory_selling_price': 'Giá bán (VND)',
    'inventory_cost_price': 'Giá vốn (VND)',
    'inventory_quantity_label': 'Số lượng hàng',
    'inventory_sort_by_name': 'Tên',
    'inventory_sort_by_quantity': 'Số lượng',
    'inventory_sort_by_category': 'Danh mục',
    'inventory_sort_by_price': 'Giá bán',
    'inventory_management_subtitle': 'Quản lý kho hàng',
    'inventory_product_label_name': 'Tên sản phẩm',
    'inventory_product_label_selling_price': 'Giá bán',
    'inventory_product_label_cost_price': 'Giá vốn',
    'product_no_products': 'Chưa có sản phẩm nào',
    'product_no_results': 'Không tìm thấy sản phẩm',
    'category_all': 'Tất cả',

    // Expenses
    'expense_amount': 'Số Tiền (VND)',
    'expense_description': 'Mô Tả',
    'expense_note': 'Ghi chú chi phí cố định',
    'expense_frequency': 'Tần Suất',
    'expense_daily': 'Hàng ngày',
    'expense_weekly': 'Hàng tuần',
    'expense_monthly': 'Hàng tháng',
    'expense_yearly': 'Hàng năm',
    'expense_start_date': 'Ngày Bắt Đầu',
    'expense_payment_method': 'Phương Thức Thanh Toán',
    'expense_cash': 'Tiền mặt',
    'expense_transfer': 'Chuyển khoản',
    'expense_card': 'Thẻ',

    // Expense Categories
    'category_rent': 'Tiền thuê',
    'category_utilities': 'Điện nước',
    'category_inventory': 'Nhập hàng',
    'category_payroll': 'Lương nhân viên',
    'category_shipping': 'Vận chuyển',
    'category_marketing': 'Marketing',
    'category_maintenance': 'Bảo trì',
    'category_office_supplies': 'Văn phòng phẩm',
    'category_food': 'Ăn uống',
    'category_other': 'Khác',
    'category_beverage': 'Đồ uống',
    'category_food_items': 'Thực phẩm',
    'category_bread': 'Bánh/Kẹo',
    'category_personal_care': 'Chăm sóc cá nhân',
    'category_household': 'Vệ sinh/Gia dụng',
    'category_electronics': 'Điện tử/Phụ kiện',

    // Statistics Page
    'stat_period_today': 'Hôm nay',
    'stat_period_this_week': 'Tuần này',
    'stat_period_this_month': 'Tháng này',
    'stat_period_last_month': 'Tháng trước',
    'stat_revenue': 'Doanh thu',
    'stat_expenses': 'Chi phí',
    'stat_profit': 'Lợi nhuận',
    'stat_items_sold': 'Đã bán',
    'stat_products': 'sản phẩm',
    'stat_quantity_sold': 'Số lượng bán ra',
    'stat_trend': 'Xu hướng Doanh thu & Chi phí',
    'stat_no_data': 'Chưa có dữ liệu để hiển thị',
    'stat_no_sales_data': 'Chưa có dữ liệu bán hàng',
    'stat_bestsellers': 'Sản phẩm bán chạy',
    'stat_quantity': 'Số lượng',
    'stat_sold': 'Đã bán',
    'stat_product_default': 'Sản phẩm',
    'stat_expense_chart': 'Biểu đồ Chi phí',
    'stat_no_expense_data': 'Chưa có dữ liệu chi phí',
    'stat_total_expenses': 'Tổng chi phí:',
    'stat_expenses_by_category': 'Chi phí theo danh mục',
    'stat_week_sold': 'bán được tuần này',
    'stat_compared_last_week': '% so với tuần trước',
    'stat_click_bar_detail': 'Nhấn vào cột để xem chi tiết',
    'stat_sold_items': 'Bán được {total} sản phẩm',
    'stat_stock_label': 'Kho:',
    'stat_custom_period': 'Tùy chỉnh',
    'error_load_data': 'Lỗi tải dữ liệu:',

    // Data Management
    'data_stats': 'Thống kê Database',
    'data_import_export': 'Copy nhanh dữ liệu sang Keto app trên máy khác',
    'data_export_file': 'Xuất file',
    'data_view_stats': 'Xem thống kê Database',
    'data_export_import_string': 'Import/Export String',
    'data_json_csv': 'JSON / CSV Export',
    'data_test_data': 'Test Thử Nghiệm App',
    'data_generate_test': 'Tạo dữ liệu để test (30 ngày)',
    'data_delete_section': 'Xóa từng phần',
    'data_delete_sales': 'Xóa tất cả dữ liệu bán hàng',
    'data_delete_expenses': 'Xóa tất cả chi phí',
    'data_danger_zone': 'Vùng nguy hiểm',
    'data_warning_banner': 'Bất kỳ thay đổi nào ở đây có thể ảnh hưởng đến tính toàn vẹn dữ liệu của bạn. Vui lòng tiến hành cẩn thận và đảm bảo bạn có bản sao lưu trước khi thực hiện bất kỳ hành động phá hủy nào.',
    'data_delete_all': 'XÓA TOÀN BỘ DATABASE',
    'data_tip': 'Gợi ý',
    'data_export_string': 'Xuất (Export)',
    'data_export_desc': 'Copy chuỗi rồi nhập vào thiết bị khác',
    'data_import_string': 'Nhập (Import)',
    'data_import_desc': 'Nhập chuỗi để copy dữ liệu',
    'data_paste_string': 'Dán chuỗi dữ liệu xuất từ thiết bị khác',
    'data_copy_string': 'Sao chép dãy ký tự ở trên rồi chép vào app Keto trên thiết bị khác',
    'data_error_empty_string': '❌ Vui lòng dán chuỗi dữ liệu',
    'data_info_title': 'Thông tin:',
    'data_products_count': 'Sản phẩm',
    'data_transactions': 'Giao dịch',
    'data_expenses': 'Chi phí',
    'data_string_length': 'Độ dài chuỗi',
    'data_character': 'ký tự',
    'data_today': 'Hôm nay:',
    'data_revenue': 'Doanh thu',
    'data_cost': 'Chi phí',
    'data_sold_items': 'Giao dịch bán',

    // Formulas
    'formula_profit_margin': 'Lợi Nhuận',
    'formula_working_capital': 'Vốn Lưu Động (Working Capital)',
    'formula_working_capital_desc': 'Số tiền có sẵn để sử dụng trong hoạt động kinh doanh hàng ngày',
    'formula_current_assets': 'Tài sản ngắn hạn',
    'formula_current_liabilities': 'Nợ ngắn hạn',
    'formula_cash': 'tiền mặt',
    'formula_inventory': 'hàng tồn kho',
    'formula_receivable': 'phải thu',

    // Validation Messages
    'error_invalid_amount': 'Số tiền không hợp lệ',
    'error_enter_amount': 'Vui lòng nhập số tiền',
    'error_loading_data': 'Lỗi tải dữ liệu',
    'error_loading_expenses': 'Lỗi tải chi tiêu: ',
    'error_adding_expense': 'Lỗi khi thêm chi tiêu',
    'error_enter_description': 'Nhập mô tả chi phí cố định',
    'error_creating_export': 'Đang tạo chuỗi export...',
    'error_with_message': 'Lỗi: ',

    // Dialogs
    'dialog_coming_soon': 'Coming Soon!',
    'dialog_pro_version': 'Bản Pro sẽ sớm ra mắt với nhiều tính năng hơn! Hãy chờ đón nhé!',
    'dialog_notification_permission': 'Yêu cầu quyền thông báo',
    'dialog_notification_message': 'Ứng dụng cần quyền gửi thông báo để nhắc nhở bạn khi hàng sắp hết. Vui lòng cấp quyền trong cài đặt.',
    'dialog_later': 'Để sau',
    'dialog_open_settings': 'Mở cài đặt',
    'dialog_confirm_delete': 'Xác nhận xóa',
    'dialog_confirm_delete_product': 'Bạn chắc chắn muốn xóa sản phẩm này?',
    'dialog_confirm_test_data': 'Tạo dữ liệu test',

    // Stock/Inventory Related
    'low_stock': 'Sắp hết hàng',
    'in_stock': 'Còn hàng',
    'stock_quantity': 'Số lượng',

    // Sales Page (ban_hang.dart)
    'sales_enter_quantity': 'Nhập số lượng',
    'sales_quantity_sold': 'Số lượng bán',
    'sales_invalid_quantity': 'Vui lòng nhập số lượng hợp lệ',
    'sales_sold': 'đã bán',
    'sales_bestselling': 'Bán chạy',
    'sales_product_name': 'Tên',
    'sales_selling_price': 'Giá bán',
    'sales_error_loading': 'Error loading data: ',
    'sales_search_product': 'Tìm kiếm mặt hàng',
    'sales_sold_today': 'Đã bán hôm nay',
    'sales_show': 'Hiển thị',
    'sales_hide': 'Ẩn',
    'sales_in_stock': 'Trong kho',
    'sales_quantity_want_to_sell': 'Số lượng muốn bán',
    'sales_no_products': 'Không tìm thấy sản phẩm',
    'sales_go_to_product_management': 'Vui lòng vào "Quản lý sản phẩm" để thêm sản phẩm',
    'sales_generate_test_data': 'Tạo dữ liệu thử nghiệm',
    'sales_please_wait': 'Vui lòng chờ trong giây lát...',
    'sales_test_data_created': 'Tạo dữ liệu thành công!',

    // Expenses Page (chi_tieu.dart)
    'expense_step1_amount': 'Bước 1: Số Tiền',
    'expense_step2_details': 'Bước 2: Chi Tiết (Tùy Chọn)',
    'expense_amount_label': 'Số Tiền (VND)',
    'expense_enter_amount': 'Vui lòng nhập số tiền',
    'expense_invalid_amount': 'Vui lòng nhập số tiền hợp lệ',
    'expense_description_label': 'Mô Tả Ngắn Gọn',
    'expense_description_hint': 'Nhập mô tả chi tiêu',
    'expense_more_details': 'Chi tiết thêm',
    'expense_note_label': 'Ghi Chú',
    'expense_note_hint': 'Thêm ghi chú (tùy chọn)',
    'expense_category': 'Loại Chi Tiêu',
    'expense_date': 'Ngày Chi Tiêu',
    'expense_select_receipt_image': 'Chọn Ảnh Hóa Đơn',
    'expense_receipt_options': 'Chọn ảnh từ',
    'expense_camera': 'Camera',
    'expense_gallery': 'Thư Viện',
    'expense_loading_image': 'Không thể tải ảnh',
    'expense_delete_expense': 'Xóa Chi Tiêu',
    'expense_continue': 'Tiếp Tục',
    'expense_back': 'Quay Lại',
    'expense_save': 'Lưu',
    'expense_cancel': 'Hủy',
    'expense_today': 'Hôm nay',
    // Expense Actions (Vietnamese)
    'expense_add': 'Thêm Chi Tiêu',
    'expense_fixed': 'Chi tiêu cố định',
    'expense_add_recurring': 'Thêm Chi Tiêu Cố Định',

    // Recurring Expense Form
    'expense_recurring_title_add': 'Thêm Chi Phí Cố Định',
    'expense_recurring_title_edit': 'Chỉnh sửa Chi Phí Cố Định',
    'expense_recurring_category': 'Danh Mục',
    'expense_recurring_status': 'Trạng Thái',
    'expense_recurring_description_label': 'Mô Tả',
    'expense_recurring_description_hint': 'Nhập mô tả chi phí cố định',
    'expense_recurring_frequency': 'Tần Suất',
    'expense_recurring_start_date': 'Ngày Bắt Đầu',
    'expense_recurring_end_date': 'Ngày Kết Thúc',
    'expense_recurring_has_end_date': 'Có ngày kết thúc',
    'expense_recurring_select_date': 'Chọn ngày',
    'expense_recurring_payment_method': 'Phương Thức Thanh Toán',
    'expense_recurring_notes': 'Ghi Chú',
    'expense_recurring_notes_hint': 'Ghi chú thêm (tùy chọn)',
    'expense_recurring_delete_confirm': 'Xác nhận xóa',
    'expense_recurring_delete_message': 'Bạn có chắc chắn muốn xóa chi phí cố định này?',

    // Main Expense View
    'expense_total_expenses': 'Tổng Chi Tiêu',
    'expense_categories_header': 'Danh Mục Chi Tiêu',
    'expense_transactions': 'giao dịch',
    'expense_transactions_plural': 'giao dịch',
    'filter_today': 'Hôm nay',
    'filter_this_week': 'Tuần này',
    'filter_this_month': 'Tháng này',
    'filter_select_date': 'Chọn ngày',

    // Fixed Expense Card (Vietnamese)
    'recurring_next_payment': 'Ngày thanh toán tiếp theo',
    'recurring_active': 'Đang hoạt động',
    'recurring_inactive': 'Đã tắt',

    // Dialog Titles & Actions (Vietnamese)
    'dialog_delete_expense': 'Xóa Chi Tiêu',
    'dialog_delete': 'Xóa',
    'dialog_close': 'Đóng',
    'dialog_detail_description': 'Mô Tả',
    'dialog_detail_amount': 'Số Tiền',
    'dialog_detail_time': 'Thời Gian',
    'dialog_detail_payment': 'Phương Thức Thanh Toán',
    'dialog_detail_note': 'Ghi Chú',
    'dialog_detail_receipt': 'Ảnh Hóa Đơn',
    'message_no_expenses': 'Chưa có chi tiêu nào',
    'message_expense_deleted': 'Chi tiêu đã được xóa',
    'message_image_load_error': 'Không thể tải ảnh',

    // Validation & Error Messages (Vietnamese)
    'error_recurring_added': 'Chi phí cố định đã được thêm',
    'error_recurring_updated': 'Chi phí cố định đã được cập nhật',
    'error_recurring_deleted': 'Chi phí cố định đã được xóa',
    'error_delete_expense_confirm': 'Bạn có chắc muốn xóa chi tiêu "{description}"?',

    // Days of week
    'day_monday': 'T2',
    'day_tuesday': 'T3',
    'day_wednesday': 'T4',
    'day_thursday': 'T5',
    'day_friday': 'T6',
    'day_saturday': 'T7',
    'day_sunday': 'CN',

    // Default values
    'default_shop_name': 'Keto - Sổ tay kinh doanh',
    'default_unit': 'cái',
  };

  // English strings
  static const Map<String, String> _english = {
    // Main Navigation
    'nav_sales': 'Sales',
    'nav_expenses': 'Expenses',
    'nav_inventory': 'Inventory',
    'nav_statistics': 'Statistics',
    'nav_product_management': 'Product Management',
    'nav_data_management': 'Data Management',
    'nav_settings': 'Settings',
    'nav_formulas': 'Basic Formulas',
    'nav_privacy': 'Privacy Policy',
    'nav_about': 'About',

    // Privacy Policy Page
    'privacy_access_title': 'Access Permissions',
    'privacy_access_content': 'The app requests access to your photo gallery when you want to add product images. You can deny this permission at any time.',
    'privacy_data_title': 'Your Data',
    'privacy_data_content': 'All your sales data is stored locally. We use Firebase for crash reporting and Google AdMob for ads. We do not share your personal data with other third parties.',
    'privacy_export_title': 'Export Data as CSV, JSON, or String',
    'privacy_export_content': 'The app allows you to export your sales data, expenses, and inventory as CSV, JSON, or String files so you can back up or use them in other applications. These files are stored on your device and are completely under your control.',
    'privacy_delete_title': 'Delete Data',
    'privacy_delete_content': 'You can delete all your data at any time through the "Data Management" option in the menu.',
    'privacy_contact_title': 'Contact',
    'privacy_contact_content': 'If you have any questions about this privacy policy, please contact us.',

    // Settings Page
    'settings_title': 'Settings',
    'settings_display': 'Display',
    'settings_shop_name': 'Shop Name',
    'settings_reset_default': 'Reset to Default',
    'settings_dark_mode': 'Dark Mode',
    'settings_on': 'On',
    'settings_off': 'Off',
    'settings_currency': 'Currency',
    'settings_select_currency': 'Select Currency',
    'settings_sound': 'Sound',
    'settings_sound_on_sale': 'Sound on Sale',
    'settings_products': 'Products',
    'settings_default_category': 'Default Product Category',
    'settings_inventory': 'Inventory',
    'settings_low_stock_threshold': 'Low Stock Threshold',
    'settings_notifications': 'Receive Inventory Notifications',
    'settings_version': 'Version $appVersion',
    'settings_language': 'Language',
    'settings_select_language': 'Select Language',

    // Common Buttons
    'btn_cancel': 'Cancel',
    'btn_back': 'Back',
    'btn_save': 'Save',
    'btn_update': 'Update',
    'btn_delete': 'Delete',
    'btn_add': 'Add',
    'btn_close': 'Close',
    'btn_ok': 'OK',
    'btn_upgrade_pro': 'Upgrade to Pro',

    // Inventory/Products
    'product_name': 'Product Name',
    'product_category': 'Category',
    'product_unit': 'Unit',
    'product_quantity': 'Quantity',
    'product_sell_price': 'Sell Price',
    'product_cost_price': 'Cost Price',
    'product_current_cost_price': 'Current Cost Price',
    'product_new_cost_price': 'New Cost Price (VND)',
    'product_note': 'Note',
    'product_categories': 'Product Categories',
    'product_other': 'Other',
    'product_add_new_title': 'Add New Product',
    'product_add_new_subtitle': 'Product Management',
    'product_empty_hint': 'Tap + to add a new product',
    'product_add_inventory_subtitle': 'Manage Inventory',
    'permission_required_title': 'Permission Required',
    'permission_gallery_message': 'App needs access to photo library to select product images. Please enable in settings.',
    'btn_open_settings': 'Open Settings',
    'product_edit_title': 'Edit Product',
    'product_edit_subtitle': 'Update Information',
    'product_select_image': 'Select Product Image',
    'product_select_image_hint': 'Tap to select image',
    'product_selling_price': 'Selling Price (VND)',
    'product_cost_price_label': 'Cost Price (VND)',
    'product_quantity_label': 'Product Quantity',
    'product_category_label': 'Category',
    'product_add_success': 'Added product "{name}" successfully',
    'product_update_success': 'Updated product "{name}" successfully',
    'product_update_error': 'Error updating product',
    'product_delete_success': 'Deleted "{name}"',
    'product_delete_error': 'Error deleting product',
    'product_delete_confirm_part1': 'Are you sure you want to delete ',
    'product_delete_confirm_part2': '? This action cannot be undone.',
    'product_delete_confirm_title': 'Confirm Delete',

    // Errors
    'error': 'Error',
    'product_fill_required_fields': 'Please fill in all required information',
    'product_price_must_positive': 'Price must be positive, quantity cannot be negative',
    'product_error_adding': 'Error adding product',
    'inventory_update_title': 'Update Inventory',
    'inventory_select_image_hint': 'Select Item Image',
    'inventory_current_stock': 'Current Stock:',
    'inventory_value': 'Current Inventory Value',
    'inventory_average_cost_price_note': 'Keto calculates AVERAGE cost price when you update inventory with a new cost price.',
    'inventory_current_cost_price_label': 'Current Cost Price:',
    'inventory_product_info': 'Current Item Info:',
    'inventory_average_cost_price': 'Average Cost Price:',
    'inventory_calculation_label': 'Calculation:',
    'inventory_calculation_formula': 'Formula: ({old_cost} × {old_quantity} + [new price] × [quantity to import]) ÷ [new total quantity]',
    'inventory_selling_price_label': 'Selling Price:',
    'inventory_update_success': 'Update inventory for "{name}" successfully\nQuantity: +{quantity}, Average Cost Price: {cost_price}',
    'inventory_update_success_simple': 'Update inventory for "{name}" successfully',
    'inventory_enter_new_quantity': 'Enter New Quantity',
    'inventory_import_different_price': 'Import at Different Price',
    'inventory_unit_hint': 'Unit (piece, kg, cup, box, portion, ...)',
    'inventory_new_cost_price': 'New Cost Price (VND)',
    'inventory_new_quantity_needed': 'New Quantity to Import',
    'inventory_current_quantity': 'Current Quantity:',
    'inventory_new_quantity': 'New Quantity:',
    'inventory_quantity_negative': 'Quantity cannot be negative',
    'inventory_quantity_greater_zero': 'Quantity must be greater than 0',
    'inventory_cost_greater_zero': 'Cost price must be greater than 0',
    'inventory_invalid_value': 'Invalid value',
    'inventory_fill_all_info': 'Please fill all information',
    'inventory_save_image_error': 'Error saving product image',
    'inventory_category_placeholder': 'Category',
    'inventory_search_placeholder': 'Search product...',
    'inventory_all_categories': 'All',
    'inventory_permission_gallery': 'App needs access to photo library to select product images. Please enable in settings.',
    'inventory_low_stock_notification': 'Low Stock',
    'inventory_out_of_stock': 'Out of Stock / Unknown Qty',
    'inventory_in_stock': 'In Stock',
    'inventory_low_stock': 'Low Stock',
    'inventory_total': 'Total',
    'inventory_in_stock_label': 'In Stock',
    'inventory_low_stock_label': 'Low Stock',
    'inventory_out_of_stock_label': 'Out of Stock /\nUnknown Qty',
    'inventory_total_value': 'Inventory Value\n(VND)',
    'inventory_quick_adjust': 'Quick Adjust:',
    'inventory_product_name': 'Product Name',
    'inventory_selling_price': 'Selling Price (VND)',
    'inventory_cost_price': 'Cost Price (VND)',
    'inventory_quantity_label': 'Quantity',
    'inventory_sort_by_name': 'Name',
    'inventory_sort_by_quantity': 'Quantity',
    'inventory_sort_by_category': 'Category',
    'inventory_sort_by_price': 'Price',
    'inventory_management_subtitle': 'Inventory Management',
    'inventory_product_label_name': 'Product Name',
    'inventory_product_label_selling_price': 'Selling Price',
    'inventory_product_label_cost_price': 'Cost Price',
    'product_no_products': 'No products yet',
    'product_no_results': 'No products found',
    'category_all': 'All',

    // Sales Page (ban_hang.dart)
    'sales_enter_quantity': 'Enter Quantity',
    'sales_quantity_sold': 'Quantity Sold',
    'sales_invalid_quantity': 'Please enter valid quantity',
    'sales_sold': 'sold',
    'sales_bestselling': 'Bestselling',
    'sales_product_name': 'Name',
    'sales_selling_price': 'Selling Price',
    'sales_error_loading': 'Error loading data: ',
    'sales_search_product': 'Search Product',
    'sales_sold_today': 'Sold Today',
    'sales_show': 'Show',
    'sales_hide': 'Hide',
    'sales_in_stock': 'In Stock',
    'sales_quantity_want_to_sell': 'Quantity to Sell',
    'sales_no_products': 'No products found',
    'sales_go_to_product_management': 'Please go to "Product Management" to add products',
    'sales_generate_test_data': 'Generate Test Data',
    'sales_please_wait': 'Please wait a moment...',
    'sales_test_data_created': 'Test data created successfully!',

    // Expenses
    'expense_amount': 'Amount (VND)',
    'expense_description': 'Description',
    'expense_note': 'Fixed Expense Note',
    'expense_frequency': 'Frequency',
    'expense_daily': 'Daily',
    'expense_weekly': 'Weekly',
    'expense_monthly': 'Monthly',
    'expense_yearly': 'Yearly',
    'expense_start_date': 'Start Date',
    'expense_payment_method': 'Payment Method',
    'expense_cash': 'Cash',
    'expense_transfer': 'Transfer',
    'expense_card': 'Card',
    'expense_step1_amount': 'Step 1: Amount',
    'expense_step2_details': 'Step 2: Details (Optional)',
    'expense_amount_label': 'Amount (VND)',
    'expense_enter_amount': 'Please enter amount',
    'expense_invalid_amount': 'Please enter valid amount',
    'expense_description_label': 'Short Description',
    'expense_description_hint': 'Enter expense description',
    'expense_more_details': 'More Details',
    'expense_note_label': 'Notes',
    'expense_note_hint': 'Add notes (optional)',
    'expense_category': 'Expense Category',
    'expense_date': 'Expense Date',
    'expense_select_receipt_image': 'Select Receipt Image',
    'expense_receipt_options': 'Select image from',
    'expense_camera': 'Camera',
    'expense_gallery': 'Gallery',
    'expense_loading_image': 'Unable to load image',
    'expense_delete_expense': 'Delete Expense',
    'expense_continue': 'Continue',
    'expense_back': 'Back',
    'expense_save': 'Save',
    'expense_cancel': 'Cancel',
    'expense_today': 'Today',
    // Expense Actions
    'expense_add': 'Add Expense',
    'expense_fixed': 'Fixed Expense',
    'expense_add_recurring': 'Add Recurring Expense',

    // Recurring Expense Form
    'expense_recurring_title_add': 'Add Fixed Expense',
    'expense_recurring_title_edit': 'Edit Fixed Expense',
    'expense_recurring_category': 'Category',
    'expense_recurring_status': 'Status',
    'expense_recurring_description_label': 'Description',
    'expense_recurring_description_hint': 'Enter fixed expense description',
    'expense_recurring_frequency': 'Frequency',
    'expense_recurring_start_date': 'Start Date',
    'expense_recurring_end_date': 'End Date',
    'expense_recurring_has_end_date': 'Has end date',
    'expense_recurring_select_date': 'Select date',
    'expense_recurring_payment_method': 'Payment Method',
    'expense_recurring_notes': 'Notes',
    'expense_recurring_notes_hint': 'Add notes (optional)',
    'expense_recurring_delete_confirm': 'Confirm Delete',
    'expense_recurring_delete_message': 'Are you sure you want to delete this fixed expense?',

    // Main Expense View
    'expense_total_expenses': 'Total Expenses',
    'expense_categories_header': 'Expense Categories',
    'expense_transactions': 'transaction',
    'expense_transactions_plural': 'transactions',
    'filter_today': 'Today',
    'filter_this_week': 'This Week',
    'filter_this_month': 'This Month',
    'filter_select_date': 'Select Date',

    // Fixed Expense Card
    'recurring_next_payment': 'Next Payment Date',
    'recurring_active': 'Active',
    'recurring_inactive': 'Inactive',

    // Dialog Titles & Actions
    'dialog_delete_expense': 'Delete Expense',
    'dialog_delete': 'Delete',
    'dialog_close': 'Close',
    'dialog_detail_description': 'Description',
    'dialog_detail_amount': 'Amount',
    'dialog_detail_time': 'Time',
    'dialog_detail_payment': 'Payment Method',
    'dialog_detail_note': 'Notes',
    'dialog_detail_receipt': 'Receipt Image',
    'message_no_expenses': 'No expenses yet',
    'message_expense_deleted': 'Expense deleted',
    'message_image_load_error': 'Unable to load image',

    // Validation & Error Messages
    'error_recurring_added': 'Fixed expense added',
    'error_recurring_updated': 'Fixed expense updated',
    'error_recurring_deleted': 'Fixed expense deleted',
    'error_delete_expense_confirm': 'Are you sure you want to delete the expense "{description}"?',

    // Expense Categories
    'category_rent': 'Rent',
    'category_utilities': 'Utilities',
    'category_inventory': 'Inventory',
    'category_payroll': 'Payroll',
    'category_shipping': 'Shipping',
    'category_marketing': 'Marketing',
    'category_maintenance': 'Maintenance',
    'category_office_supplies': 'Office Supplies',
    'category_food': 'Food/Dining',
    'category_other': 'Other',
    'category_beverage': 'Beverages',
    'category_food_items': 'Food',
    'category_bread': 'Baked goods/Candy',
    'category_personal_care': 'Personal care',
    'category_household': 'Household supplies',
    'category_electronics': 'Electronics/Accessories',

    // Statistics Page
    'stat_period_today': 'Today',
    'stat_period_this_week': 'This Week',
    'stat_period_this_month': 'This Month',
    'stat_period_last_month': 'Last Month',
    'stat_revenue': 'Revenue',
    'stat_expenses': 'Expenses',
    'stat_profit': 'Profit',
    'stat_items_sold': 'Sold',
    'stat_products': 'products',
    'stat_quantity_sold': 'Quantity Sold',
    'stat_trend': 'Revenue & Expense Trend',
    'stat_no_data': 'No data to display',
    'stat_no_sales_data': 'No sales data',
    'stat_bestsellers': 'Bestsellers',
    'stat_quantity': 'Quantity',
    'stat_sold': 'Sold',
    'stat_product_default': 'Product',
    'stat_expense_chart': 'Expense Chart',
    'stat_no_expense_data': 'No expense data',
    'stat_total_expenses': 'Total Expenses:',
    'stat_expenses_by_category': 'Expenses by Category',
    'stat_week_sold': 'sold this week',
    'stat_compared_last_week': '% compared to last week',
    'stat_click_bar_detail': 'Click on a bar to see details',
    'stat_sold_items': 'Sold {total} products',
    'stat_stock_label': 'Stock:',
    'stat_custom_period': 'Custom',
    'error_load_data': 'Error loading data:',

    // Data Management
    'data_stats': 'Database Statistics',
    'data_import_export': 'Quickly copy data to Keto app on another device',
    'data_export_file': 'Export File',
    'data_view_stats': 'View Database Statistics',
    'data_export_import_string': 'Import/Export String',
    'data_json_csv': 'JSON / CSV Export',
    'data_test_data': 'Test App',
    'data_generate_test': 'Generate Test Data (30 days)',
    'data_delete_section': 'Delete Sections',
    'data_delete_sales': 'Delete All Sales Data',
    'data_delete_expenses': 'Delete All Expenses',
    'data_danger_zone': 'Danger Zone',
    'data_warning_banner': 'Any changes made here can affect your data integrity. Please proceed with caution and ensure you have backups before performing any destructive actions.',
    'data_delete_all': 'DELETE ENTIRE DATABASE',
    'data_tip': 'Tip',
    'data_export_string': 'Export',
    'data_export_desc': 'Copy string then import to another device',
    'data_import_string': 'Import',
    'data_import_desc': 'Import string to copy data',
    'data_paste_string': 'Paste data string here',
    'data_copy_string': 'Copy the string above and paste it in another device to copy database',
    'data_error_empty_string': '❌ Please paste a data string',
    'data_info_title': 'Info:',
    'data_products_count': 'Products',
    'data_transactions': 'Transactions',
    'data_expenses': 'Expenses',
    'data_string_length': 'String Length',
    'data_character': 'characters',
    'data_today': 'Today:',
    'data_revenue': 'Revenue',
    'data_cost': 'Cost',
    'data_sold_items': 'Sales Transactions',

    // Formulas
    'formula_profit_margin': 'Profit Margin',
    'formula_working_capital': 'Working Capital',
    'formula_working_capital_desc': 'Money available for daily business operations',
    'formula_current_assets': 'Current Assets',
    'formula_current_liabilities': 'Current Liabilities',
    'formula_cash': 'cash',
    'formula_inventory': 'inventory',
    'formula_receivable': 'receivable',

    // Validation Messages
    'error_invalid_amount': 'Invalid amount',
    'error_enter_amount': 'Please enter amount',
    'error_loading_data': 'Error loading data',
    'error_loading_expenses': 'Error loading expenses: ',
    'error_adding_expense': 'Error adding expense',
    'error_enter_description': 'Enter fixed expense description',
    'error_creating_export': 'Creating export string...',
    'error_with_message': 'Error: ',

    // Dialogs
    'dialog_coming_soon': 'Coming Soon!',
    'dialog_pro_version': 'Pro version coming soon with more features!',
    'dialog_notification_permission': 'Notification Permission',
    'dialog_notification_message': 'App needs notification permission to remind you about low stock. Please grant permission in settings.',
    'dialog_later': 'Later',
    'dialog_open_settings': 'Open Settings',
    'dialog_confirm_delete': 'Confirm Delete',
    'dialog_confirm_delete_product': 'Are you sure you want to delete this product?',
    'dialog_confirm_test_data': 'Generate Test Data',

    // Stock/Inventory Related
    'low_stock': 'Low Stock',
    'stock_quantity': 'Quantity',

    // Days of week
    'day_monday': 'Mon',
    'day_tuesday': 'Tue',
    'day_wednesday': 'Wed',
    'day_thursday': 'Thu',
    'day_friday': 'Fri',
    'day_saturday': 'Sat',
    'day_sunday': 'Sun',

    // Default values
    'default_shop_name': 'Keto - Business Notebook',
    'default_unit': 'piece',
  };

  /// Get localized string by key
  static String getString(String key) {
    if (language == 'en') {
      return _english[key] ?? key;
    } else {
      return _vietnamese[key] ?? key;
    }
  }

  /// Get localized string with optional parameters
  static String getStringWithParams(String key, Map<String, String> params) {
    String value = getString(key);
    params.forEach((k, v) {
      value = value.replaceAll('{$k}', v);
    });
    return value;
  }

  /// Set language
  static void setLanguage(String lang) {
    if (lang == 'vi' || lang == 'en') {
      language = lang;
    }
  }

  /// Get available languages
  static List<String> getAvailableLanguages() {
    return ['vi', 'en'];
  }

  /// Get language display name
  static String getLanguageDisplayName(String lang) {
    return lang == 'vi' ? 'Tiếng Việt' : 'English';
  }

  /// Convert Vietnamese product category to localized category name
  /// Maps Vietnamese category names stored in database to localization keys
  static String getLocalizedProductCategory(String vietnameseCategory) {
    const categoryMapping = {
      'Đồ uống': 'category_beverage',
      'Thực phẩm': 'category_food_items',
      'Bánh/Kẹo': 'category_bread',
      'Chăm sóc cá nhân': 'category_personal_care',
      'Vệ sinh/Gia dụng': 'category_household',
      'Điện tử/Phụ kiện': 'category_electronics',
      'Khác': 'category_other',
    };

    final key = categoryMapping[vietnameseCategory];
    if (key != null) {
      return getString(key);
    }
    // If category not found in mapping, return the original Vietnamese name
    return vietnameseCategory;
  }
}
